name: mobileapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.6.0
  flutter_stripe: ^11.5.0
  curved_navigation_bar: ^1.0.6
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  image_picker: ^1.1.2 
  firebase_storage: ^12.4.8
  random_string: ^2.3.1
  shared_preferences: ^2.5.3
  http: ^1.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
fonts:
  - family: Roboto
    fonts: 
      - asset: fonts/Roboto.zip
